name: dart_coin_rpc
description: A simple RPC client for bitcoin-like coins created in dart.
version: 2.1.5
homepage: https://github.com/Vesta-wallet/dart-coin-rpc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^5.1.1
  dio_smart_retry: ^5.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4