name: bitcoinrpc
description: A simple RPC client for bitcoin created in dart.
version: 1.0.8
# homepage: https://www.example.com
repository: https://github.com/Dolaned/dart-eccoin-rpc

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
 path: ^1.7.0
 logger: ^0.9.4
 intl: ^0.16.1
 http: ^0.12.2
 http_auth: ^0.3.1




dev_dependencies:
  pedantic: ^1.9.0

