name: dart_coin_rpc
description: A simple RPC client for bitcoin-like coins created in dart.
version: 2.1.0
homepage: https://github.com/Vesta-wallet/dart-coin-rpc

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4