
name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      peercoind:
        image: peercoin/peercoind:latest
        environment:       
          - RPC_USER=rpc
          - RPC_PASSWORD=password
        ports:
          - 9902:9902

  run-dart-tests: 
    runs-on: ubuntu-latest
    steps:
    - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

    - name: Install dependencies
      run: dart pub get

    - name: Analyze project source
      run: dart analyze

    - name: Run tests
      run: dart test