name: Tests
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      peercoind:
        image: 'peercoin/peercoind:latest'
        env:
          RPC_USER: rpc
          RPC_PASSWORD: password
        ports:
          - '9902:9902'
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.5.0
      - name: Install dependencies
        run: dart pub get
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart test
